"""create_councils_and_defense_schedules_tables

Revision ID: 42bf19499107
Revises: 9b2f4c7d1a6e
Create Date: 2026-08-13 02:03:10.459172
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '42bf19499107'
down_revision: str | None = '9b2f4c7d1a6e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestones',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestones'))
    )
    op.create_table('councils',
    sa.Column('academic_period_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_room', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='councilstatus', native_enum=False), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_period_id'], ['academic_periods.id'], name=op.f('fk_councils_academic_period_id_academic_periods'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_councils_created_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_councils')),
    sa.UniqueConstraint('academic_period_id', 'code', name='uq_councils_period_code')
    )
    op.create_index(op.f('ix_councils_academic_period_id'), 'councils', ['academic_period_id'], unique=False)
    op.create_index(op.f('ix_councils_status'), 'councils', ['status'], unique=False)
    op.create_table('council_members',
    sa.Column('council_id', sa.UUID(), nullable=False),
    sa.Column('lecturer_id', sa.UUID(), nullable=False),
    sa.Column('member_role', sa.Enum('CHAIRPERSON', 'SECRETARY', 'REVIEWER', 'MEMBER', name='councilmemberrole', native_enum=False), nullable=False),
    sa.Column('assigned_by_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'REMOVED', name='councilmemberstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_council_members_assigned_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['council_id'], ['councils.id'], name=op.f('fk_council_members_council_id_councils'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['users.id'], name=op.f('fk_council_members_lecturer_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_council_members')),
    sa.UniqueConstraint('council_id', 'lecturer_id', name='uq_council_members_council_lecturer')
    )
    op.create_index(op.f('ix_council_members_council_id'), 'council_members', ['council_id'], unique=False)
    op.create_index(op.f('ix_council_members_lecturer_id'), 'council_members', ['lecturer_id'], unique=False)
    op.create_index(op.f('ix_council_members_member_role'), 'council_members', ['member_role'], unique=False)
    op.create_table('reports',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_reports_student_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_reports_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index('reports_student_idx', 'reports', ['student_id'], unique=False)
    op.create_index('reports_topic_idx', 'reports', ['topic_id'], unique=False)
    op.create_table('defense_schedules',
    sa.Column('council_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=False),
    sa.Column('presentation_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'POSTPONED', name='defenseschedulestatus', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['council_id'], ['councils.id'], name=op.f('fk_defense_schedules_council_id_councils'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_defense_schedules_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('fk_defense_schedules_registration_id_registrations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_defense_schedules'))
    )
    op.create_index(op.f('ix_defense_schedules_council_id'), 'defense_schedules', ['council_id'], unique=False)
    op.create_index(op.f('ix_defense_schedules_registration_id'), 'defense_schedules', ['registration_id'], unique=False)
    op.create_table('progress_logs',
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('teacher_comment', sa.Text(), nullable=True),
    sa.Column('commented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('fk_progress_logs_milestone_id_milestones'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('fk_progress_logs_registration_id_registrations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_progress_logs_student_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_logs'))
    )
    op.create_index('progress_logs_registration_idx', 'progress_logs', ['registration_id'], unique=False)
    op.create_index('progress_logs_student_idx', 'progress_logs', ['student_id'], unique=False)
    op.drop_constraint(op.f('ck_registrations_supervisor_required_when_approved_or_i_ba70'), 'registrations', type_='check')
    op.create_check_constraint(op.f('ck_registrations_supervisor_required_when_approved_or_in_progress'), 'registrations', "status NOT IN ('approved', 'in_progress') OR supervisor_id IS NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_registrations_supervisor_required_when_approved_or_in_progress'), 'registrations', type_='check')
    op.create_check_constraint(op.f('ck_registrations_supervisor_required_when_approved_or_i_ba70'), 'registrations', "(status <> ALL (ARRAY['approved'::registration_status, 'in_progress'::registration_status])) OR supervisor_id IS NOT NULL")
    op.drop_index('progress_logs_student_idx', table_name='progress_logs')
    op.drop_index('progress_logs_registration_idx', table_name='progress_logs')
    op.drop_table('progress_logs')
    op.drop_index(op.f('ix_defense_schedules_registration_id'), table_name='defense_schedules')
    op.drop_index(op.f('ix_defense_schedules_council_id'), table_name='defense_schedules')
    op.drop_table('defense_schedules')
    op.drop_index('reports_topic_idx', table_name='reports')
    op.drop_index('reports_student_idx', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_council_members_member_role'), table_name='council_members')
    op.drop_index(op.f('ix_council_members_lecturer_id'), table_name='council_members')
    op.drop_index(op.f('ix_council_members_council_id'), table_name='council_members')
    op.drop_table('council_members')
    op.drop_index(op.f('ix_councils_status'), table_name='councils')
    op.drop_index(op.f('ix_councils_academic_period_id'), table_name='councils')
    op.drop_table('councils')
    op.drop_table('milestones')
    # ### end Alembic commands ###
