"""add council_type to councils

Revision ID: 663056e13f16
Revises: 8f176f3bd889
Create Date: 2026-09-24 10:58:30.819858
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '663056e13f16'
down_revision: str | None = '8f176f3bd889'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('councils', sa.Column('council_type', sa.Enum('DEFENSE', 'ACCEPTANCE', name='counciltype', native_enum=False), nullable=False))
    op.drop_constraint(op.f('ck_defense_schedules_defense_schedule_presentation_orde_d492'), 'defense_schedules', type_='check')
    op.create_check_constraint(op.f('ck_defense_schedules_defense_schedule_presentation_order_positive'), 'defense_schedules', 'presentation_order IS NULL OR presentation_order >= 1')
    op.drop_constraint(op.f('ck_registrations_supervisor_required_when_approved_or_i_ba70'), 'registrations', type_='check')
    op.create_check_constraint(op.f('ck_registrations_supervisor_required_when_approved_or_in_progress'), 'registrations', "status NOT IN ('approved', 'in_progress') OR supervisor_id IS NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_registrations_supervisor_required_when_approved_or_in_progress'), 'registrations', type_='check')
    op.create_check_constraint(op.f('ck_registrations_supervisor_required_when_approved_or_i_ba70'), 'registrations', "(status <> ALL (ARRAY['approved'::registration_status, 'in_progress'::registration_status])) OR supervisor_id IS NOT NULL")
    op.drop_constraint(op.f('ck_defense_schedules_defense_schedule_presentation_order_positive'), 'defense_schedules', type_='check')
    op.create_check_constraint(op.f('ck_defense_schedules_defense_schedule_presentation_orde_d492'), 'defense_schedules', 'presentation_order IS NULL OR presentation_order >= 1')
    op.drop_column('councils', 'council_type')
    # ### end Alembic commands ###
