"""create_core_database_foundation

Revision ID: 70eec2ac9b85
Revises:
Create Date: 2026-08-05 15:35:10.078518
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '70eec2ac9b85'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('institutional_code', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('student', 'lecturer', 'admin', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'locked', name='user_status'), server_default='active', nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('institutional_code', name=op.f('uq_users_institutional_code'))
    )
    op.create_index('users_full_name_idx', 'users', ['full_name'], unique=False)
    op.create_index('users_role_idx', 'users', ['role'], unique=False)
    op.create_index('users_status_idx', 'users', ['status'], unique=False)
    op.create_table('academic_periods',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.SmallInteger(), nullable=True),
    sa.Column('proposal_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('proposal_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registration_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registration_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('execution_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('defense_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('defense_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'proposal_open', 'registration_open', 'in_progress', 'defense', 'completed', 'cancelled', name='academic_period_status'), server_default='draft', nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('defense_start_at IS NULL OR defense_end_at IS NULL OR defense_start_at < defense_end_at', name=op.f('ck_academic_periods_defense_time_order')),
    sa.CheckConstraint('execution_start_at IS NULL OR execution_end_at IS NULL OR execution_start_at < execution_end_at', name=op.f('ck_academic_periods_execution_time_order')),
    sa.CheckConstraint('proposal_start_at < proposal_end_at', name=op.f('ck_academic_periods_proposal_time_order')),
    sa.CheckConstraint('registration_start_at < registration_end_at', name=op.f('ck_academic_periods_registration_time_order')),
    sa.CheckConstraint('semester IS NULL OR semester BETWEEN 1 AND 3', name=op.f('ck_academic_periods_semester_range')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_academic_periods_created_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_periods')),
    sa.UniqueConstraint('code', name=op.f('uq_academic_periods_code'))
    )
    op.create_index('academic_periods_academic_year_idx', 'academic_periods', ['academic_year'], unique=False)
    op.create_index('academic_periods_registration_time_idx', 'academic_periods', ['registration_start_at', 'registration_end_at'], unique=False)
    op.create_index('academic_periods_status_idx', 'academic_periods', ['status'], unique=False)
    op.create_table('topics',
    sa.Column('academic_period_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('max_students', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('proposed_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending_approval', 'approved', 'rejected', 'closed', 'cancelled', 'completed', name='topic_status'), server_default='pending_approval', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status != 'rejected' OR rejection_reason IS NOT NULL", name=op.f('ck_topics_rejection_reason_required_when_rejected')),
    sa.CheckConstraint("status NOT IN ('approved', 'closed') OR approved_by_id IS NOT NULL", name=op.f('ck_topics_approved_by_required_when_approved_or_closed')),
    sa.CheckConstraint('max_students >= 1', name=op.f('ck_topics_max_students_positive')),
    sa.ForeignKeyConstraint(['academic_period_id'], ['academic_periods.id'], name=op.f('fk_topics_academic_period_id_academic_periods'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_topics_approved_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['users.id'], name=op.f('fk_topics_proposed_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('academic_period_id', 'code', name=op.f('uq_topics_academic_period_id'))
    )
    op.create_index('topics_period_idx', 'topics', ['academic_period_id'], unique=False)
    op.create_index('topics_proposed_by_idx', 'topics', ['proposed_by_id'], unique=False)
    op.create_index('topics_status_idx', 'topics', ['status'], unique=False)
    op.create_index('topics_title_idx', 'topics', ['title'], unique=False)
    op.create_table('registrations',
    sa.Column('academic_period_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('supervisor_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', 'in_progress', 'completed', name='registration_status'), server_default='pending', nullable=False),
    sa.Column('student_note', sa.Text(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supervisor_assigned_by_id', sa.UUID(), nullable=True),
    sa.Column('supervisor_assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status != 'cancelled' OR cancelled_at IS NOT NULL", name=op.f('ck_registrations_cancelled_at_required_when_cancelled')),
    sa.CheckConstraint("status != 'rejected' OR reviewed_at IS NOT NULL", name=op.f('ck_registrations_reviewed_at_required_when_rejected')),
    sa.CheckConstraint("status NOT IN ('approved', 'in_progress') OR supervisor_id IS NOT NULL", name=op.f('ck_registrations_supervisor_required_when_approved_or_in_progress')),
    sa.ForeignKeyConstraint(['academic_period_id'], ['academic_periods.id'], name=op.f('fk_registrations_academic_period_id_academic_periods'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_registrations_reviewed_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_registrations_student_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supervisor_assigned_by_id'], ['users.id'], name=op.f('fk_registrations_supervisor_assigned_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], name=op.f('fk_registrations_supervisor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_registrations_topic_id_topics'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registrations'))
    )
    op.create_index('registrations_one_effective_per_student_period', 'registrations', ['student_id', 'academic_period_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'approved', 'in_progress')"))
    op.create_index('registrations_period_idx', 'registrations', ['academic_period_id'], unique=False)
    op.create_index('registrations_status_idx', 'registrations', ['status'], unique=False)
    op.create_index('registrations_student_idx', 'registrations', ['student_id'], unique=False)
    op.create_index('registrations_supervisor_idx', 'registrations', ['supervisor_id'], unique=False)
    op.create_index('registrations_topic_idx', 'registrations', ['topic_id'], unique=False)
    op.create_index('registrations_topic_status_idx', 'registrations', ['topic_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('registrations_topic_status_idx', table_name='registrations')
    op.drop_index('registrations_topic_idx', table_name='registrations')
    op.drop_index('registrations_supervisor_idx', table_name='registrations')
    op.drop_index('registrations_student_idx', table_name='registrations')
    op.drop_index('registrations_status_idx', table_name='registrations')
    op.drop_index('registrations_period_idx', table_name='registrations')
    op.drop_index('registrations_one_effective_per_student_period', table_name='registrations', postgresql_where=sa.text("status IN ('pending', 'approved', 'in_progress')"))
    op.drop_table('registrations')
    op.drop_index('topics_title_idx', table_name='topics')
    op.drop_index('topics_status_idx', table_name='topics')
    op.drop_index('topics_proposed_by_idx', table_name='topics')
    op.drop_index('topics_period_idx', table_name='topics')
    op.drop_table('topics')
    op.drop_index('academic_periods_status_idx', table_name='academic_periods')
    op.drop_index('academic_periods_registration_time_idx', table_name='academic_periods')
    op.drop_index('academic_periods_academic_year_idx', table_name='academic_periods')
    op.drop_table('academic_periods')
    op.drop_index('users_status_idx', table_name='users')
    op.drop_index('users_role_idx', table_name='users')
    op.drop_index('users_full_name_idx', table_name='users')
    op.drop_table('users')
    sa.Enum(name='registration_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='topic_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='academic_period_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='user_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
