"""add report_type to reports

Revision ID: 8f176f3bd889
Revises: c2f4e8a9b1d3
Create Date: 2026-09-24 10:52:04.232137
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8f176f3bd889'
down_revision: str | None = 'c2f4e8a9b1d3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_defense_schedules_defense_schedule_presentation_orde_d492'), 'defense_schedules', type_='check')
    op.create_check_constraint(op.f('ck_defense_schedules_defense_schedule_presentation_order_positive'), 'defense_schedules', 'presentation_order IS NULL OR presentation_order >= 1')
    op.drop_constraint(op.f('ck_registrations_supervisor_required_when_approved_or_i_ba70'), 'registrations', type_='check')
    op.create_check_constraint(op.f('ck_registrations_supervisor_required_when_approved_or_in_progress'), 'registrations', "status NOT IN ('approved', 'in_progress') OR supervisor_id IS NOT NULL")
    op.add_column('reports', sa.Column('report_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'report_type')
    op.drop_constraint(op.f('ck_registrations_supervisor_required_when_approved_or_in_progress'), 'registrations', type_='check')
    op.create_check_constraint(op.f('ck_registrations_supervisor_required_when_approved_or_i_ba70'), 'registrations', "(status <> ALL (ARRAY['approved'::registration_status, 'in_progress'::registration_status])) OR supervisor_id IS NOT NULL")
    op.drop_constraint(op.f('ck_defense_schedules_defense_schedule_presentation_order_positive'), 'defense_schedules', type_='check')
    op.create_check_constraint(op.f('ck_defense_schedules_defense_schedule_presentation_orde_d492'), 'defense_schedules', 'presentation_order IS NULL OR presentation_order >= 1')
    # ### end Alembic commands ###
